<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle("Gerenciar Tickets")->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon-32x32.png'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/menu.css'))
            ->prependStylesheet($this->basePath('css/charts.css'))
        ?>

        <!-- Scripts -->
        <?= $this->inlineScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.3.1.min.js'))
            ->prependFile($this->basePath('js/menu.js'))
            ->prependFile($this->basePath('js/charts.js'))
        ?>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.5.1/chart.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
        <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    </head>
    <body style="margin: 0; padding: 0;">
        <nav class="navbar collapse navbar-collapse no-margin navbar-expand-lg navbar-dark fixed-top bg-dark" role="navigation" style="margin: 0; padding: 0; border: 0; border-radius: 0;">
            <div class="container" style="margin-left: 0;">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <button class="navbar-toggle collapse in" data-toggle="collapse" id="menu-toggle-2">
                                <span><i class="fa fa-bars" aria-hidden="true" style="color: white; font-size: 25px;"></i></span>
                            </button>
                        </ul>
                    </div>
                </div>
                <div class="navbar-header">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/favicon-32x32.png') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Gerenciar Tickets
                    </a>
                </div>
            </div>
        </nav>

        <div id="wrapper" class="wrapper">
            <!-- Sidebar -->
            <div id="sidebar-wrapper">
                <ul class="sidebar-nav nav-pills nav-stacked" id="menu">
                    <li>
                        <a href="<?= $this->url('home') ?>">
                            <span class="fa-stack fa-lg pull-left">
                                <i class="fa fa-home fa-stack-1x"></i>
                            </span> Home
                        </a>
                    </li>
                    <li>
                        <a href="<?= $this->url('tickets') ?>">
                            <span class="fa-stack fa-lg pull-left">
                                <i class="fa fa-ticket fa-stack-1x"></i>
                            </span>Tickets
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('tickets', ['action' => 'relatorio'])?>">
                            <span class="fa-stack fa-lg pull-left">
                                <i class="fa fa-file-pdf-o fa-stack-1x"></i>
                            </span>Relatório
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('tickets', ['action' => 'upgrade'])?>">
                            <span class="fa-stack fa-lg pull-left">
                                <i class="fa fa-cart-plus fa-stack-1x"></i>
                            </span>Upgrade
                        </a>
                    </li>
                    <li>
                        <a href="<?=$this->url('tickets', ['action' => 'manuais'])?>">
                            <span class="fa-stack fa-lg pull-left">
                                <i class="fa fa-play-circle fa-stack-1x"></i>
                            </span>Manuais
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg pull-left">
                                <i class="fa fa-wrench fa-stack-1x"></i>
                            </span>Configurações
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="fa-stack fa-lg pull-left">
                                <i class="fa fa-server fa-stack-1x"></i>
                            </span>Suporte
                        </a>
                    </li>
                </ul>
            </div>
            <div class="page-content-wrapper">
                <div class="container-fluid xyz">
                    <div class="row">
                        <div class="col-lg-12">
                            <?= $this->content ?>
                            <hr>
                            <footer class="footer mt-auto bg-light">
                                <span class="text-muted p-y"><p>&copy; <?= date('Y') ?> | Daniel Lima Ltd | All rights reserved.</p></span>
                            </footer>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>