<h1 class="mb-4">Configurações</h1><hr>
<div class="mb-1">
  <div class="card border-5 pt-2 active pb-0 px-3 bg-primary-new">
    <div class="card-body ">
      <div class="row">
        <div class="col-12 ">
          <h4 class="card-title "><b>Módulo: Clientes</b></h4>
        </div>
        <div class="col">
          <h6 class="card-subtitle mb-2 text-muted">
            <p class="card-text text-muted small ">
              <img src="https://img.icons8.com/metro/26/000000/star.png" class="mr-1 " width="19"
                height="19" id="star"> <span class="vl mr-2 ml-0"></span>
              <span class="font-weight-bold"> BBBootstrap Team</span> on 1 Nov , 2018
            </p>
          </h6>
        </div>
      </div>
    </div>
    <div class="card-footer bg-white px-3">
      <div class="row">
        <div class=" col-md-auto ">
          <a href="#" class="btn btn-outlined btn-black text-muted bg-transparent"
            data-wow-delay="0.7s"><img src="https://img.icons8.com/ios/50/000000/settings.png"
            width="19" height="19"> <small>Expandir</small></a>
          <i class="mdi mdi-settings-outline"></i>

          <a href="#" class="btn btn-outlined btn-black text-muted bg-transparent"
            data-wow-delay="0.7s"><img src="https://img.icons8.com/metro/26/000000/link.png"
            width="17" height="17" id="plus"> <small>Vincular</small></a>
          <i class="mdi mdi-settings-outline"></i>
          <a href="#" class="btn btn-outlined btn-black text-muted "><img
            src="https://img.icons8.com/metro/26/000000/more.png" width="20" height="20"
            class="mr-2 more"><small>Mais</small></a>
          <span class="vl ml-3"></span>
        </div>
        <div class="col-md-auto ">
          <ul class="list-inline">
            <li class="list-inline-item"> <img
              src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1573035860/Pra/Hadie-profile-pic-circle-1.png"
              alt="DP" class="  rounded-circle img-fluid " width="35" height="35">
            </li>
            <li class="list-inline-item"> <img src="https://img.icons8.com/ios/50/000000/plus.png"
              width="30" height="30 " class="more">
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="card mt-5 border-5 pt-2 active pb-0 px-3 bg-primary-new">
    <div class="card-body ">
      <div class="row">
        <div class="col-12 ">
          <h4 class="card-title "><b>Módulo: Usuários</b></h4>
        </div>
        <div class="col">
          <h6 class="card-subtitle mb-2 text-muted">
            <p class="card-text text-muted small ">
              <img src="https://img.icons8.com/color/26/000000/christmas-star.png" class="mr-1 "
                width="19" height="19" id="star"> <span class="vl mr-2 ml-0"></span>
              <span class="font-weight-bold"> BBBootstrap Team</span> on 1 Nov , 2018
            </p>
          </h6>
        </div>
      </div>
    </div>
    <div class="card-footer bg-white px-3">
      <div class="row">
        <div class=" col-md-auto ">
          <a href="#" class="btn btn-outlined btn-black text-muted bg-transparent"
            data-wow-delay="0.7s"><img src="https://img.icons8.com/ios/50/000000/settings.png"
            width="19" height="19"> <small>Expandir</small></a>
          <i class="mdi mdi-settings-outline"></i>

          <a href="#" class="btn btn-outlined btn-black text-muted bg-transparent"
            data-wow-delay="0.7s"><img src="https://img.icons8.com/metro/26/000000/link.png"
            width="17" height="17" id="plus"> <small>Vincular</small></a>
          <i class="mdi mdi-settings-outline"></i>
          <a href="#" class="btn btn-outlined btn-black text-muted "><img
            src="https://img.icons8.com/metro/26/000000/more.png" width="20" height="20"
            class="mr-2 more"><small>Mais</small></a>
          <span class="vl ml-3"></span>
        </div>
        <div class="col-md-auto ">
          <ul class="list-inline">
            <li class="list-inline-item"> <img
              src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1573035860/Pra/Hadie-profile-pic-circle-1.png"
              alt="DP" class="  rounded-circle img-fluid " width="35" height="35">
              <img src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1573035909/Pra/Loren-profile-pic-circle.png"
                alt="DP" class="  rounded-circle img-fluid " width="35" height="35">
              <img src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1573035929/Pra/59d280613165c000014cc031_circleniamhhogan.png"
                alt="DP" class="  rounded-circle img-fluid " width="35" height="35">
              <img src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1573035929/Pra/59d280613165c000014cc031_circleniamhhogan.png"
                alt="DP" class="  rounded-circle img-fluid " width="35" height="35">
            </li>
            <li class="list-inline-item"> <img src="https://img.icons8.com/ios/50/000000/plus.png"
              width="30" height="30 " class="more">
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="card mt-5 border-5 pt-2 active pb-0 px-3 bg-primary-new">
    <div class="card-body ">
      <div class="row">
        <div class="col-12 ">
          <h4 class="card-title "><b>Módulo: Integrações</b></h4>
        </div>
      </div>
    </div>
    <div class="card-footer bg-white px-3 border-radius-10">
      <div class="row">
        <div class=" col-md-auto ">
          <a href="#" class="btn btn-outlined btn-black text-muted bg-transparent"
            data-wow-delay="0.7s"><img src="https://img.icons8.com/ios/50/000000/settings.png"
            width="19" height="19"> <small>Expandir</small></a>
          <i class="mdi mdi-settings-outline"></i>

          <a href="#" class="btn btn-outlined btn-black text-muted bg-transparent"
            data-wow-delay="0.7s"><img src="https://img.icons8.com/metro/26/000000/link.png"
            width="17" height="17" id="plus"> <small>Vincular</small></a>
          <i class="mdi mdi-settings-outline"></i>
          <a href="#" class="btn btn-outlined btn-black text-muted "><img
            src="https://img.icons8.com/metro/26/000000/more.png" width="20" height="20"
            class="mr-2 more"><small>Mais</small></a>
          <span class="vl ml-3"></span>
        </div>
        <div class="col-md-auto ">
          <ul class="list-inline">
            <li class="list-inline-item"> <img
              src="https://res.cloudinary.com/dxfq3iotg/image/upload/v1573035929/Pra/59d280613165c000014cc031_circleniamhhogan.png"
              alt="DP" class="  rounded-circle img-fluid " width="35" height="35">
            </li>
            <li class="list-inline-item"> <img src="https://img.icons8.com/ios/50/000000/plus.png"
              width="30" height="30 " class="more">
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>