<h1 class="mb-4">Gerenciamento</h1>
<table class="table table-stripped table-hover">
	<tr>
		<th>ID</th>
		<th>Nome</th>
		<th>Setor</th>
		<th>Prioridade</th>
		<th>Data</th>
		<th></th>
	</tr>
	<?php
		foreach ($tickets as $key => $pes) {
			echo '<tr>';
				echo '<td>'.$pes->getId().'</td>';
				echo '<td>'.$pes->getName().'</td>';
				echo '<td>'.$pes->getSector().'</td>';
				echo '<td>'.$pes->getPriority().'</td>';
				echo '<td>'.format_data($pes->getCreated_at()).'</td>';
				echo '<td>';
				?>
				<a href="<?=$this->url('tickets', ['action'=>'editar', 'id' => $pes->getId()])?>" class="btn btn-primary-new">
					<i class="fa fa-pencil-square-o" aria-hidden="true"></i>
				</a>
				<a href="<?=$this->url('tickets', ['action'=>'remover', 'id' => $pes->getId()])?>" class="btn btn-danger">
					<i class="fa fa-trash-o" aria-hidden="true"></i>
				</a>
				<?php
				echo '</a></td>';
			echo '</tr>';
		}
	?>
</table>
<a href="<?=$this->url('tickets', ['action' => 'adicionar'])?>" class="btn btn-primary-new">
	<i class="fa fa-plus" aria-hidden="true"></i>
</a>

<?php
	function format_data($date)
	{
		$date = new DateTime($date);
		$date_format = $date->format('d/m/Y');
		return $date_format;
	}
?>