<h1 class="mb-5">Relatórios</h1>
<div class="col-sm-12 mt-5">
    <div class="col-sm-6">
        <div class="chart">
            <canvas id="myChart" width="400" height="200"></canvas>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="chart-container">
            <canvas id="chart" width="400" height="200"></canvas>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="chart-container">
            <canvas id="chart2" width="400" height="200"></canvas>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="chart-container">
            <canvas id="myChart4" width="400" height="200"></canvas>
        </div>
    </div>
</div>