<div class="w-table">
  <div class="w-table-cell">
    <div class="w-container">
      <div class="w-card color-violet">
        <div class="card-header">
          <div class="w-title">
            Básico
          </div>
          <div class="w-price">
            R$99.99
          </div>
          <div class="container-button">
            <a class="w-button">Avaliar </a>
          </div>
        </div>
        <div class="card-content">
          <div class="w-item">
            <span>1GB </span>Disk Space 
          </div>
          <div class="w-item">
            <span>10GB </span>Monthly Bandwidth 
          </div>
          <div class="w-item">
            <span>1 </span>Email Accounts 
          </div>
        </div>
      </div>
      <div class="w-card color-green">
        <div class="card-header">
          <div class="w-title">
            Standard
          </div>
          <div class="w-price">
            R$199.99
          </div>
          <div class="container-button">
            <div class="w-button">
              Avaliar
            </div>
          </div>
        </div>
        <div class="card-content">
          <div class="w-item">
            <span>2GB </span>Disk Space 
          </div>
          <div class="w-item">
            <span>25GB </span>Monthly Bandwidth 
          </div>
          <div class="w-item">
            <span>2 </span>Email Accounts 
          </div>
        </div>
      </div>
      <div class="w-card color-blue">
        <div class="card-header">
          <div class="w-title">
            Professional
          </div>
          <div class="w-price">
            R$299.99
          </div>
          <div class="container-button">
            <div class="w-button">
              Avaliar
            </div>
          </div>
        </div>
        <div class="card-content">
          <div class="w-item">
            <span>5GB </span>Disk Space 
          </div>
          <div class="w-item">
            <span>50GB </span>Monthly Bandwidth 
          </div>
          <div class="w-item">
            <span>10 </span>Email Accounts 
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="jumbotron">
    <h2>Mais controle para sua empresa, mais <span class="title-green">satisfação para seu cliente</span></h2>

    <h5>
        Sua equipe precisa de mais organização e seus clientes querem a melhor experiência possível. Tenha tudo isso em um só lugar.
        <a href="<?= $this->url('tickets') ?>" class="title-green">Organize os chamados e ofereça o melhor suporte com o sistema de tickets</a>.
    </h5>

    <p><a class="btn btn-primary-new btn-lg" href="<?= $this->url('tickets') ?>">Gerenciar &raquo;</a></p>
</div>
<style type="text/css">
  @import url(https://fonts.googleapis.com/css?family=Roboto:400,300,500);
  .color-violet .container-button {
  background-color: #98f;
  }
  .color-violet .container-button:before {
  background-color: #98f;
  }
  .color-violet .w-item span {
  color: #98f;
  }
  .color-green .container-button {
  background-color: #1bbc9d;
  }
  .color-green .container-button:before {
  background-color: #1bbc9d;
  }
  .color-green .w-item span {
  color: #1bbc9d;
  }
  .color-red .container-button {
  background-color: #DB343A;
  }
  .color-red .container-button:before {
  background-color: #DB343A;
  }
  .color-red .w-item span {
  color: #DB343A;
  }
  .color-pink .container-button {
  background-color: #E91E63;
  }
  .color-pink .container-button:before {
  background-color: #E91E63;
  }
  .color-pink .w-item span {
  color: #E91E63;
  }
  .color-blue .container-button {
  background-color: #3498db;
  }
  .color-blue .container-button:before {
  background-color: #3498db;
  }
  .color-blue .w-item span {
  color: #3498db;
  }
  .w-table {
  display: table;
  width: 100%;
  }
  .w-table-cell {
  display: table-cell;
  vertical-align: middle;
  }
  .w-container {
  position: relative;
  max-width: 100%;
  margin: 30px auto 0;
  font-size: 0;
  text-align: center;
  }
  .w-container .w-card {
  cursor: pointer;
  background-color: #fff;
  display: inline-block;
  vertical-align: top;
  width: 300px;
  color: #333;
  font-size: 30px;
  font-weight: 300;
  margin: 0 0 30px;
  -moz-transition: all 0.3s;
  -o-transition: all 0.3s;
  -webkit-transition: all 0.3s;
  transition: all 0.3s;
  }
  .w-container .w-card .card-header {
  overflow: hidden;
  padding: 20px 0 0;
  }
  .w-container .w-card .card-header .w-title, .w-container .w-card .card-header .w-price {
  position: relative;
  z-index: 2;
  }
  .w-container .w-card .card-header .w-price {
  font-size: 42px;
  font-weight: 500;
  padding: 1px 20px 20px;
  }
  .w-container .w-card .card-content {
  padding: 20px;
  }
  .w-container .w-card .card-content .w-item {
  font-size: 20px;
  padding: 10px;
  border-bottom: 1px solid #ddd;
  }
  .w-container .w-card .card-content .w-item:last-child {
  border-bottom: none;
  }
  .w-container .w-card .card-content .w-item span {
  font-weight: 500;
  }
  .w-container .w-card .container-button {
  position: relative;
  }
  .w-container .w-card .container-button .w-button {
  position: relative;
  display: block;
  padding: 20px;
  color: #fff;
  font-weight: 400;
  z-index: 2;
  text-decoration: none;
  -moz-transition: all 0.3s;
  -o-transition: all 0.3s;
  -webkit-transition: all 0.3s;
  transition: all 0.3s;
  }
  .w-container .w-card .container-button:before, .w-container .w-card .container-button:after {
  content: "";
  position: absolute;
  top: 0px;
  left: 50%;
  width: 0%;
  height: 0%;
  border-radius: 50%;
  -moz-transition: all 0.3s;
  -o-transition: all 0.3s;
  -webkit-transition: all 0.3s;
  transition: all 0.3s;
  }
  .w-container .w-card .container-button:after {
  z-index: 1;
  background-color: rgba(255, 255, 255, 0.1);
  -moz-transition: all 0.5s;
  -o-transition: all 0.5s;
  -webkit-transition: all 0.5s;
  transition: all 0.5s;
  }
  .w-container .w-card .container-button:hover .w-button {
  padding: 0px 20px 40px;
  }
  .w-container .w-card .container-button:hover:before {
  top: -200px;
  left: -50px;
  width: 400px;
  height: 400px;
  }
  .w-container .w-card .container-button:hover:after {
  top: -200px;
  left: -50px;
  width: 400px;
  height: 400px;
  }
  .w-container .w-card:hover {
  z-index: 2;
  margin: -20px 0 50px;
  }
  .w-container .w-card:hover .w-button {
  opacity: 1;
  }
</style>