<header></header>
<div class="jumbotron">
    <h1>Mais controle para sua empresa, mais <span class="title-green">satisfação para seu cliente</span></h1>

    <p>
        Sua equipe precisa de mais organização e seus clientes querem a melhor experiência possível. Tenha tudo isso em um só lugar.
        <a href="<?= $this->url('tickets') ?>" class="title-green">Organize os chamados e ofereça o melhor suporte com o sistema de tickets</a>.
    </p>

    <p><a class="btn btn-primary-new btn-lg" href="<?= $this->url('tickets') ?>">Gerenciar &raquo;</a></p>
</div>
